Add probabilistic F1 score
piotr-rarus/kaggle-rsna-breast-cancer pull request #9
Opened 2022-12-07 18:09 UTC by ojqbo

2022-12-07 18:13 UTC, piotr-rarus requested changes

2022-12-07 18:13 UTC, piotr-rarus commented on src/lib/metrics.py
> +def foo(a: int) -> int:
bonk

2022-12-07 18:13 UTC, piotr-rarus commented on src/lib/metrics.py
> +    for idx in range(len(labels)):
maybe numpy would be better? no iterating over lists

2022-12-07 18:13 UTC, piotr-rarus commented on src/lib/tests/test_metrics.py
> +def test_foo() -> None:
bonk

2022-12-07 18:13 UTC, piotr-rarus commented on src/lib/metrics.py
> +    else:
Inverse condition, remove nested conditions.
https://www.youtube.com/watch?v=CFRhGnuXG-4

2022-12-07 18:14 UTC, piotr-rarus commented on src/lib/metrics.py
> +def foo(a: int) -> int:
![image](https://user-images.githubusercontent.com/44392988/206262974-0213813e-d21b-4236-a199-08c56b24d500.png)

2022-12-07 20:18 UTC, piotr-rarus commented on src/lib/metrics.py
> +    labels: NDArray[np.int_], preds: NDArray[np.float_], beta: float = 1.0
Czym się różni `np.int_` od `np.int`?

2022-12-07 22:57 UTC, ojqbo commented on src/lib/metrics.py
> +    labels: NDArray[np.int_], preds: NDArray[np.float_], beta: float = 1.0
`np.int` to alias do pythonowego `int`'a, dodatkowo `np.int` jest `Deprecated in NumPy 1.20`  i użycie go wyrzuca warningi nakazujące używać samego `int` w mniejsce `np.int`.
`np.int_` to alias to `int`'a używanego wewnątrz NumPy (jest to `int` znany z C, a nie z Pythona, który miałby nieograniczoną precyzję), u mnie `np.int_` to alias do typu `numpy.int64`.

Użycie `NDArray[int]` lub `NDArray[np.int]` wyrzuci błąd przy `make build`, podczas komendy:  
`poetry run mypy --incremental --install-types --show-error-codes --pretty src`

2022-12-16 06:32 UTC, piotr-rarus commented on notebooks/differentiable_pfbeta.ipynb
> +    "# In this notebook we try to come up with pF1 score that will be differentiable for any input\n",
Daj jakiś normalny nagłówek: `Probabilistic F1 studies`, a ten tekst w komórce niżej jako tekst.

2022-12-16 06:32 UTC, piotr-rarus commented on pyproject.toml
> +torch = "^1.13.1"
Proszę posortować dependency ;)

2022-12-16 06:32 UTC, piotr-rarus commented on src/lib/metrics.py
> +        # Yet returned in this way, it has the same partial derivatives
Tu nagle duża litera `Yet`. Może byłoby lepiej zrobić docstringa?

2022-12-16 07:04 UTC, ojqbo commented on pyproject.toml
> +torch = "^1.13.1"
to teraz nie jest posortowane?

2022-12-16 11:32 UTC, piotr-rarus commented on pyproject.toml
> +torch = "^1.13.1"
wybacz, mózg mi wyparował :D:D

2022-12-20 10:39 UTC, piotr-rarus approved these changes

2022-12-20 10:40 UTC, merged